### ISSUE TITLE
Why do you only release "release candidates"?

### ISSUE THREAD

**Issue by GeneGeneGitHub** [jonmacs/jove#12]
/eom

**Comment by markmoraes** [comment]
:shrug: lack of testers, or well-defined release process.  Figuring out how to resume packaging for various distros (other than Debian, which Cord covers, and FreeBSD, which I think Paul handles, both from pre-releases?) is on my to-do list, but alas, pretty far down.  Volunteers for release help are welcome, of course.

**Comment by The-Informaticist** [comment]
I'd be glad to be a tester for you, although right now I only have a Windows 10 setup. It would be a great learning experience for me, and hopefully would help others, too.

**Comment by markmoraes** [comment]
I've stopped calling them candidates as of 4.17.5.2, but the process I use isn't that much different -- some testing of my own on a few OS containers & VMs.

**Comment by vixie** [comment]
Ty 


p vixie 


On Mar 19, 2023 21:30, markmoraes ***@***.***> wrote: 

Closed #12 as completed.
